blogapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'blogapp'

urlpatterns = [
    path('about/', views.about_view, name='about'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('', views.home_view, name='home'),
    path('<slug:slug>/', views.detail_view, name='detail'),
    path('category/<slug:category_slug>/', views.category_view, name='category'),
    path('tags/<slug:tag_slug>/', views.home_view, name='posts_by_tag'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
    path('create/add_category/', views.CreateCategoryView.as_view(), name='add_category'),
    path('add_bookmark/<slug:slug>/', views.add_bookmark, name='add_bookmark'),
    path('remove_bookmark/<slug:slug>/', views.remove_bookmark, name='remove_bookmark'),
    path('post/bookmarks/', views.bookmarked_posts, name='bookmarks'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),


]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blogapp.sitemaps import PostSitemap

sitemaps = {
    'items': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp')),
    path('auth/', include('user.urls', namespace='user')),
    path('tinymce/', include('tinymce.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.register_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),

]

templates/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}

<html lang="en">
<head>
<title>
Weblogapp-learning from us
	</title>
	<meta name="description"
		  content="Weblogapp provides tutorials to enable rapid learning">
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.6.0/styles/a11y-dark.css">
	<script src="https://kit.fontawesome.com/66af27bf36.js" crossorigin="anonymous"></script>
</head>
<body>

<header>
	<nav class="container">

			<a href="{% url 'blogapp:home'%}" class="brand">Weblogapp</a>


		<button class="nav-toggler">
				<span></span>
			</button>

		<div class="nav-menu">
			<ul>
			<li><a href="{% url 'blogapp:home'%}">Home</a></li>

			 {% if user.is_staff %}
      <li><a href="{% url 'blogapp:create' %}">Create Post</a></li>

      {% endif %}

				{% if user.is_authenticated %}
				<li><a href="{% url 'user:logout' %}" class="logout">Logout</a></li>
				<li><a href="{% url 'blogapp:bookmarks' %}">Bookmarked Posts</a></li>

{% else %}
				<li><a href="{% url 'user:login' %}" class="login">Login</a></li>
				<li><a href="{% url 'user:signup' %}" class="signup">Sign Up</a></li>

{% endif %}
		</ul>
		</div>


	</nav>
</header>



 {% block main %}


  {% endblock %}





<footer>
		<div class="footer-top container">
			<div class="footer-wrapper">

				<a href="{% url 'blogapp:home' %}" class="brand">Weblogapp</a>

			</div>


       <div class="footer-wrapper">
<a href="{% url 'blogapp:about' %}" class="footer-link">About Us</a>

            <a href="{% url 'blogapp:terms' %}" class="footer-link">Terms of use</a>
		   <a href="{% url 'blogapp:privacy' %}" class="footer-link">Privacy Policy</a>

      </div>


		</div>

		<div class="footer-bottom container">
			<p class="copyright">
      &copy; Copyright 2022 <a href="{% url 'blogapp:home'%}">Weblogapp</a>
    </p>
		</div>
	</footer>


 {% block javascript %}
    <script src="{% static 'js/script.js' %}"></script>
    {% endblock javascript %}

<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/highlight.min.js"></script>

<script>
	hljs.initHighlightingOnLoad();
</script>

</body>
</html>