blogapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name= 'blogapp'

urlpatterns = [
    path('about/', views.about_view, name='about'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('', views.home_view, name='home'),
    path('<slug:slug>/', views.detail_view, name='detail'),
    path('category/<slug:category_slug>/', views.category_view, name='category'),
    path('tags/<slug:tag_slug>/', views.home_view, name='posts_by_tag'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
    path('create/add_category/', views.CreateCategoryView.as_view(), name='add_category'),
    path('add_bookmark/<slug:slug>/', views.add_bookmark, name='add_bookmark'),
    path('remove_bookmark/<slug:slug>/', views.remove_bookmark, name='remove_bookmark'),
    path('post/bookmarks/', views.bookmarked_posts, name='bookmarks'),
    path('post/<slug:slug>/like/', views.like_post, name='like_post'),


]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blogapp.sitemaps import PostSitemap

sitemaps = {
    'items': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp')),
    path('auth/', include('user.urls', namespace='user')),
    path('tinymce/', include('tinymce.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('signup/', views.register_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),

]

blogapp/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=150, null=False, blank=False)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    class Meta:
        ordering=('-name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            super(Category, self).save(*args, **kwargs)

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, null=True, related_name="posts", blank=True,
                                 on_delete=models.SET_NULL)
    tags = TaggableManager()
    content = HTMLField(blank=True, null=True)
    image = models.ImageField(upload_to='static/images', blank=True, null=True)
    image_credit = models.URLField(null=True, help_text="paste or type the link(optional)", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog')
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(default=timezone.now)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogapp:detail', args=[self.slug])

    class Meta:
        ordering = ['date_created']
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, null=True)
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self', null=True, related_name='replies', on_delete=models.CASCADE)

    class Meta:
        ordering = ['date_created']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'



class About(models.Model):
    body = HTMLField(blank=True, null=True)

class Terms(models.Model):
    body = HTMLField(blank=True, null=True)

    class Meta:
        verbose_name = 'Terms'
        verbose_name_plural = 'Terms'

class Privacy(models.Model):
    body = HTMLField(blank=True, null=True)

    class Meta:
        verbose_name = 'Privacy'
        verbose_name_plural = 'Privacies'

blogapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Category, Comment, About, Privacy, Terms


class CreateForm(ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'category', 'tags', 'content', 'image', 'image_credit', 'status']


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']


class AboutForm(ModelForm):
    class Meta:
        model = About
        fields = '__all__'

class PrivacyForm(ModelForm):
    class Meta:
        model = Privacy
        fields = '__all__'

class TermForm(ModelForm):
    class Meta:
        model = Terms
        fields = '__all__'

blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from .models import Post, Category, Comment, Bookmark, About, Privacy, Terms
from .forms import CreateForm, CommentForm, AboutForm, PrivacyForm, TermForm
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse


def home_view(request, tag_slug=None):
    # display only published posts
    object_list = Post.objects.filter(status=1).order_by('-date_created')
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags=tag)
        
    # pagination
    paginator = Paginator(object_list, 4)
    page = request.GET.get('page')
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return render(request, 'blogapp/home.html', {'object_list': object_list,
                                                 'page': page, 'all_tags': all_tags,
                                                 'categories': categories,
                                                 'tag': tag})



def category_view(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    object_list = Post.objects.all()
    all_tags = Tag.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)
    return render(request, 'blogapp/category.html', {'category': category,
                                                     'categories': categories
        , 'object_list': object_list,
        'all_tags': all_tags})



def detail_view(request, slug, *args, **kwargs):
    post = get_object_or_404(Post, slug=slug)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    is_bookmarked = request.user.is_authenticated and post.id in request.user.bookmark_set.values_list('post__id', flat=True)
    comments = post.comments.filter(active=True, parent__isnull=True)
    new_comment = None
    comment_count = post.comments.count()
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = get_object_or_404(Comment, id=parent_id)
                if parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.parent = parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, "your comment was sucessfully uploaded!")
            return redirect('blogapp:detail', slug=post.slug)
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)  # related posts
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags')[:4]  # related posts

    return render(request, 'blogapp/detail.html', {'post': post, 'all_tags': all_tags,
                                                   'categories': categories,
                                                   'similar_posts': similar_posts,
                                                   'comments': comments,
                                                   'new_comment':new_comment,
                                                   'comment_form': comment_form,
                                                   'comment_count': comment_count,
                                                    'is_bookmarked': is_bookmarked
                                                   })


class CreatePostView(CreateView):
    model = Post
    template_name = 'blogapp/create.html'
    context_object_name = 'blog_list'
    fields = ['title', 'category', 'tags', 'content', 'image', 'image_credit', 'status']
    success_url = reverse_lazy('blogapp:home')
    
    def form_valid(self, form):
        # Setting the author to the current user
        form.instance.author = self.request.user  
        return super().form_valid(form)



class CreateCategoryView(CreateView):
    model = Category
    template_name = 'blogapp/add_category.html'
    fields = ['name',]
    success_url = reverse_lazy('blogapp:create')

class EditView(UpdateView):
    model = Post
    template_name = 'blogapp/edit_post.html'
    fields = ['title', 'category', 'tags', 'content', 'image', 'image_credit', 'author']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('blogapp:home')

class Delete(DeleteView):
    model = Post
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('blogapp:home')
    template_name = 'blogapp/delete.html'

# post bookmarking functionality
@login_required
def add_bookmark(request, slug):
    post = get_object_or_404(Post, slug=slug)
    bookmark, created = Bookmark.objects.get_or_create(user=request.user, post=post)
    # Handle case if already bookmarked
    return redirect('blogapp:detail', slug=post.slug)

@login_required
def remove_bookmark(request, slug):
    post = get_object_or_404(Post, slug=slug)
    bookmark = Bookmark.objects.filter(user=request.user, post=post).first()
    if bookmark:
        bookmark.delete()
    # Handle case if not bookmarked
    return redirect('blogapp:detail', slug=post.slug)

@login_required
def bookmarked_posts(request):
    bookmarks = Bookmark.objects.filter(user=request.user)
    return render(request, 'blogapp/bookmarked_posts.html', {'bookmarks': bookmarks})


# like posts functionality
@login_required
def like_post(request, slug):
    # check if it is a post request and ajax request
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        post = get_object_or_404(Post, slug=slug)
        user = request.user

        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True

        post.save()

        return JsonResponse({'liked': liked, 'count': post.likes.count()})
    else:
        return JsonResponse({'error': _('Invalid request')}, status=400)


def about_view(request):
    about = About.objects.all().first()
    if request.method == 'POST':
        form = AboutForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = AboutForm()
    return render(request, 'blogapp/about.html', {'form': form, 'about': about})

def terms_view(request):
    terms = Terms.objects.all().first()
    if request.method == 'POST':
        form = TermForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TermForm()
    return render(request, 'blogapp/terms.html', {'form': form, 'terms': terms})

def privacy_view(request):
    privacy = Privacy.objects.all().first()
    if request.method == 'POST':
        form = PrivacyForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = PrivacyForm()
    return render(request, 'blogapp/privacy.html', {'form': form, 'privacy': privacy})



def error_404(request, exception):
    return render(request, '404.html')

blogapp/templates/blogapp/category.html
{% extends 'base.html' %} {% block main %}

<main>
  {% if category %}
  <div class="container" style="margin-bottom: 1rem; color: #6e7780">
    <p><a href="{% url 'blogapp:home'%}">Home</a>/ category/ {{category}}</p>
  </div>
  {% endif %}

  <div class="container">
    <section>
      <div class="main-wrapper">
        {% if object_list %} {% for blog in object_list %}

        <!--  blog card -->
        <div class="blog-card">
          <div>
            {% if blog.image %}<a href="{{ blog.get_absolute_url }}">
              <img src="{{ blog.image.url }}" class="blog-card-img" /></a
            >{% endif %}
          </div>
          <div class="card-content">
            <a href="{% url 'blogapp:category' blog.category.slug %}" class="category"
              >{{ blog.category }}</a>
            <a href="{{ blog.get_absolute_url }}" class="card-title"
              ><h3>{{ blog.title }}</h3></a
            >

            <p>
              {{blog.content|safe|truncatewords:14}}
              <a href="{{ blog.get_absolute_url }}" class="read-more"
                >Read more</a
              >
            </p>
          </div>
        </div>
        <!-- end blog card -->

        {% endfor %} {% else %}
        <strong>no posts in {{ category.name }}</strong>

        {% endif %}
      </div>
      <!--end main wrapper-->
      {% include 'blogapp/pagination.html' %}
    </section>

    {% include 'blogapp/sidebar.html' %}
  </div>
</main>

{% endblock %}

blogapp/templates/blogapp/create.html
{% extends 'base.html' %} {% block main %}
<main class="main">
  <div class="wrapper">
    <h2 style="margin-bottom: 0.8rem">Create Post</h2>
    <p>
      didn't find your category?
      <a href="{% url 'blogapp:add_category' %}">add new category</a>
    </p>
    <form method="post" class="post-form" enctype="multipart/form-data">
      {% csrf_token %} {{ form.media }} {{form.as_p}}

      <div>
        <button class="button primary" type="submit">Create Post</button>

        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
      </div>
    </form>
  </div>
</main>
{% endblock %}

blogapp/templates/blogapp/detail.html
<!DOCTYPE html>
{% load blog_tags %} {% load static %} 
<html lang="en">
  <head>
    <title>{% block title %} {{ post.title }} {% endblock %}</title>
    <meta name="description" content="{{post.content|safe|truncatewords:14}}" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/highlight.js@11.6.0/styles/a11y-dark.css"
    />
    <style>
      .liked {
        color: #fff;
        background-color: #3944bc;
      }
    </style>
    
  </head>
  <body>

<header>
	<nav class="container">

			<a href="{% url 'blogapp:home'%}" class="brand">Weblogapp</a>


		<button class="nav-toggler">
				<span></span>
			</button>

		<div class="nav-menu">
			<ul>
			<li><a href="{% url 'blogapp:home'%}">Home</a></li>

			 {% if user.is_staff %}
      <li><a href="{% url 'blogapp:create' %}">Create Post</a></li>
      {% endif %}

				{% if user.is_authenticated %}
				<li><a href="{% url 'user:logout' %}" class="logout">Logout</a></li>
        <li><a href="{% url 'blogapp:bookmarks' %}">Bookmarked Posts</a></li>

{% else %}
				<li><a href="{% url 'user:login' %}" class="login">Login</a></li>
				<li><a href="{% url 'user:signup' %}" class="signup">Sign Up</a></li>

{% endif %}
		</ul>
		</div>


	</nav>
</header>

    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {% endfor %} {% endif %} {% block main %}

    <main>
      <div class="container">
        <article>
          <div class="article-header">
            <a href="{% url 'blogapp:category' post.category.slug %}" class="category"
              >{{ post.category }}</a
            >

            <h1>{{ post.title }}</h1>

            <p class="post-timing">
              by {{post.author}}<span>&bull; </span>{{post.date_created|date}}
            </p>

            {% if post.image %}<img
              src="{{ post.image.url }}"
              class="header-img"
            />{% endif %} {% if post.image_credit %}
            <p class="credit">
              image credit:
              <a href="{{post.image_credit}}">{{post.image_credit}}</a>
            </p>
            {% endif %}
          </div>

          <div class="main-detail">{{ post.content|safe }}</div>

          <!-- end main detail -->

          <!-- bookmark -->
          
    
 <div>
          {% if request.user.is_authenticated %}
          {% if is_bookmarked %}
              <a href="{% url 'blogapp:remove_bookmark' slug=post.slug %}" class="button primary"><svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-bookmark-check" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
              </svg></a>
          {% else %}
              <a href="{% url 'blogapp:add_bookmark' slug=post.slug %}" class="button primary"><svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z"/>
              </svg></a>
          {% endif %}
      {% endif %}

      <button  style="display:inline-block;" id="like-button" data-post-id="{{ post.slug }}" {% if request.user in post.likes.all %}class="liked button" {% else %} class="button" {% endif %}>
        {% if request.user in post.likes.all %}Unlike{% else %}Like{% endif %}
      </button>
      <span id="like-count">{{ post.likes.count }} Likes</span>

 </div>


          <div class="article-tag-box" style="margin-top:1rem;">
            <h3>Tags</h3>
            {% for tag in post.tags.all %}
            <a href="{% url 'blogapp:posts_by_tag' tag.slug %}" class="tag-link"
              >#{{tag.name}}</a
            >
            {% endfor %}
          </div>

          <div class="article-bottom">
            {% if user.is_staff %}
            <div class="link-group">
              <a href="{% url 'blogapp:edit' post.pk %}" class="button primary">Edit</a>
              <a href="{% url 'blogapp:delete' post.pk %}" class="button error"
                >Delete</a
              >
            </div>
            {% endif %}
          </div>
          <!-- end article bottom -->

          <div class="similar">
            <h2>Similar Posts</h2>
            <div class="similar-wrapper">
              {% for post in similar_posts %}
              <div class="similar-post-card">
                {% if post.image %}<img src="{{post.image.url}}" />{% endif %}
                <div class="card-content">
                  <a
                    href="{{ post.get_absolute_url }}"
                    class="similar-post-title"
                  >
                    <h3>{{post.title}}</h3>
                  </a>
                  <p class="similar-post-date">{{post.date_created|date}}</p>
                </div>
              </div>
              {% empty %} no similar posts yet. {% endfor %}
            </div>
          </div>

          <div class="comment-wrapper">
            <h2>Comments</h2>
             {% if not user.is_authenticated %}
            <small>please <a href="{% url 'user:login'%}">login</a> to make comments</small>
            {% endif %}
            {% for comment in comments %}
            <div class="comment">
              <div class="comment-body">
                <div class="comment-header">
                  <p>
                    <strong class="comment-name">{{ comment.name }}</strong>
                    <small class="timing">
                      &bull; {{comment.date_created|timesince }} ago</small
                    >
                  </p>
                </div>

                <p>{{comment.body}}</p>

                  {% if user.is_authenticated %}
                <button
                  class="show-reply-form"
                  style="
                    padding: 3px 8px;
                    cursor: pointer;
                    font-weight: 500;
                    margin-bottom: 1.2rem;
                    border: 1px solid #6e7780;
                  "
                >
                  reply
                </button>
                <div class="accordion-content">
                  <form method="post" action="." class="comment-form post-form">
                    <h3>reply</h3>
                    {% csrf_token %} {{comment_form.as_p}}
                    <!--parent comment.id -->
                    <input
                      type="hidden"
                      name="parent_id"
                      value="{{ comment.id }}"
                    />
                    <button class="button primary" type="submit" value="Reply">
                      Reply
                    </button>
                  </form>
                </div>
              </div>
              <!--end comment body-->

            {% endif %}
              {% for reply in comment.replies.all %}
              <div class="comment-body" style="margin-left: 45px">
                <div class="comment-header">
                  <p>
                    <strong class="comment-name">{{ reply.name }}</strong>
                    <small class="timing">
                      &bull; {{reply.date_created|timesince }} ago</small
                    >
                  </p>
                </div>

                <p>{{reply.body}}</p>

                {% if user.is_authenticated %}
                <button
                  class="show-reply-form"
                  style="
                    padding: 3px 8px;
                    cursor: pointer;
                    font-weight: 500;
                    margin-bottom: 1rem;
                    border: 1px solid #6e7780;
                  "
                >
                  reply
                </button>

                <div class="accordion-content">
                  <form method="post" action="." class="comment-form post-form">
                    <h3>reply</h3>
                    {% csrf_token %} {{comment_form.as_p}}
                    <!--parent comment.id -->
                    <input
                      type="hidden"
                      name="parent_id"
                      value="{{ comment.id }}"
                    />
                    <button class="button primary" type="submit" value="Reply">
                      Reply
                    </button>
                  </form>
                </div>
              </div>


            {% endif %}

              {% endfor %}
            </div>
            {% endfor %}
            <!--end comment-->
          </div>
          <!--end comment wrapper-->

          <div class="comment-form-wrapper" style="margin-top: 3rem">
             {% if user.is_authenticated %}
            <h2>Leave a reply</h2>

            <form id="comment-form" method="post" action="." class="comment-form post-form">
              {% csrf_token %} {{comment_form.as_p}}
              <button class="button primary" type="submit">Comment</button>
            </form>
            {% endif %}
          </div>

          <!--end detail wrapper-->
        </article>
        {% include 'blogapp/sidebar.html' %}
      </div>
    </main>

    {% endblock %}

    <footer>
      <div class="footer-top container">
        <div class="footer-wrapper">
          <a href="{% url 'blogapp:home' %}" class="brand">Weblogapp</a>
        </div>

        <div class="footer-wrapper">
          <a href="{% url 'blogapp:about' %}" class="footer-link">About Us</a>

          <a href="{% url 'blogapp:terms' %}" class="footer-link">Terms of use</a>
          <a href="{% url 'blogapp:privacy' %}" class="footer-link">Privacy Policy</a>
        </div>
      </div>

      <div class="footer-bottom container">
        <p class="copyright">
          &copy; Copyright 2022 <a href="{% url 'blogapp:home'%}">Weblogapp</a>
        </p>
      </div>
    </footer>

    

    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/highlight.min.js"></script>

    <script>
      hljs.initHighlightingOnLoad();
    </script>

    <script>
      const accord = document.getElementsByClassName('show-reply-form');
let i;

for (i = 0; i < accord.length; i++) {
	accord[i].addEventListener("click", function(){
		this.classList.toggle("active");
		let reply = this.nextElementSibling;
		if (reply.style.display === "block"){
			reply.style.display = "none";

		}else{
			reply.style.display = "block";
		}
	});
}
    </script>


    {% block javascript %}
    <script src="{% static 'js/script.js' %}"></script>
    {% endblock javascript %}

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
      $(document).ready(function(){
        $('#like-button').click(function(){
          var post_slug = "{{ post.slug }}";
          var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    
          $.ajax({
            type: 'POST',
            url: '/post/' + post_slug + '/like/',
            headers: { "X-CSRFToken": csrftoken },
            success: function(data){
              if (data.liked) {
                $('#like-button').addClass('liked').text('Unlike');
              } else {
                $('#like-button').removeClass('liked').text('Like');
              }
              
              $('#like-count').text(data.count + ' Likes');
            },
            error: function(xhr, errmsg, err){
              console.log(err);
            }
          });
        });
      });
    </script>

  </body>
</html>

blogapp/templates/blogapp/edit_post.html
{% extends 'base.html' %} {% block main %}
<main class="main">
  <div class="wrapper">
    <h2 style="margin-bottom: 0.8rem">Update Post</h2>
    <p>
      didn't find your category?
      <a href="{% url 'blogapp:add_category' %}">add new category</a>
    </p>
    <form method="post" class="post-form" enctype="multipart/form-data">
      {% csrf_token %} {{ form.media }} {{form.as_p}}

      <div>
        <button class="button primary" type="submit">Update Post</button>

        <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
      </div>
    </form>
  </div>
</main>
{% endblock %}

blogapp/templates/blogapp/latest_posts.html
{% for post in latest_posts %}
<li class="recent-post">
  <span>&bull;</span>
  <a href="{{post.get_absolute_url}}" class="recent-post-link">
    {{post.title}}</a
  >
</li>
{% endfor %}

blogapp/templates/blogapp/sidebar.html
{% load blog_tags %}
<aside>
  <div class="side-box">
    <h2>Browse Categories</h2>
    {% for category in categories %}
    <a href="{% url 'blogapp:category' category.slug %}" class="category-link"
      >{{category.name}}</a
    >
    {% endfor %}
  </div>

  <div class="side-box">
    <h2>Tags</h2>
    {% for tag in all_tags %}
    <a href="{% url 'blogapp:posts_by_tag' tag.slug %}" class="tag-link"
      >#{{tag.name}}</a
    >

    {% endfor %}
  </div>

  <div class="side-box">
    <h2>Recent Posts</h2>

    {% show_latest_posts 4 %}
  </div>
</aside>